include $(CHPL_MAKE_HOME)/make/compiler/Makefile.gnu

CLOC=$(THIRD_PARTY_DIR)/hsa/cloc/bin/cloc.sh
HOF=$(THIRD_PARTY_DIR)/hsa/HSA-HOF-AMD/bin/hof
CLOC_FLAGS=
HOF_FLAGS=

LIBS+=-lhsa-runtime64 -lhsa-ext-finalize64 -lhsa-ext-image64 -lhsakmt -lm
GEN_LFLAGS+=-L$(THIRD_PARTY_DIR)/hsa/HSA-Runtime-AMD/lib
HSA_INCLUDES=-I$(THIRD_PARTY_DIR)/hsa/HSA-Runtime-AMD/include
